### ISSUE TITLE
Get mapping quality_level

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-oceanography-qc-tools#12]
quality_level are hard to understand it would be good to have a more descriptive label for each of them

**Comment by JessyBarrette** [comment]
This is the quality levels associated to the samples

```
quality_levels = [
    "Raw",
    "Technician",
    "Technicianm",
    "Technicianr",
    "Technicianmr",
    "Principal Investigator",
]
```
@fostermh do you know if there's a defined label somewhere for terms?

**Comment by JessyBarrette** [comment]
I guess this is mostly to represent the levels =    
- "Technician",
- "Technicianm",
- "Technicianr",
- "Technicianmr",

For which I personnally have no idea of the signification.

**Comment by CarrieWeekes** [comment]
Hey Jessy, my understanding is that these different levels allow folks to track the status of the metadata & data. As things go through different levels of QC they get updated accordingly.

**Comment by JessyBarrette** [comment]
Sounds good 

From @CarrieWeekes  to help tracking info

Quality Level Descriptions
- Raw = collected but no event QC / nothing has been done yet.
- Technician m = metadata Rechecked & potentially moved post-survey?
- Technician mr = metadata results Results back from UBC/UA matched with metadata
- Technician r = results Results are there but metadata hasn’t been QC’d (not usually the case)
- Principal Investigator = paper / data product ready Data has gone through nutrient QC routines using Jessy’s QC tool

Wiley suggested that a PI or someone who has experience with the data/QC process needs to check off on this final quality level flagging

**Comment by JessyBarrette** [comment]
I added a description of the different quality_levels when your mouse hovers over the selection dropdown. We can improve that eventually.
