### ISSUE TITLE
CTD qc 

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-oceanography-qc-tools#16]
Add method to generate automated manual qc based on the automated flag

**Comment by JessyBarrette** [comment]
This is now generated

**Comment by JessyBarrette** [comment]
@ah-hakai a new method to automatically fill the qc flags regarding the ctd data is now available. 

The method for now has the ability to generate a flag and a comment.

So far, the following conditions are executed:
- default flag: median flag associated with the automated qc flag
For temperature and salinity:
- If 0 to less than 4 records bin are flagged with a density inversion, add a comment `Some density inversion are present.`
- If 4 or more records bin are flagged with a density inversion, add a comment `A significant number of density inversion are present.` and flag profile as `SVC`

@ah-hakai let me know if you'd like something else.

**Comment by ah-hakai** [comment]
Jessy, that sounds pretty good. I'm wondering if the size of the density
inversion is more important than how many there are. But we can use this
approach for now.

Alex

**Comment by JessyBarrette** [comment]
Sounds good I'll close this issue for now.
